---
abstract: 'Given a starting date, a number of days and a list of days to be skipped, returns the date X number of days away.'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.002
  Test::Deep: 0
  Test::More: 0.94
  Test::NoWarnings: 0
  Test::UseAllModules: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Duration-SkipDays
no_index:
  directory:
    - t
    - xt
requires:
  Carp: 0
  DateTime: 0
  DateTime::Event::Holiday::US: 0
  DateTime::Format::Flexible: 0
  List::MoreUtils: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
version: 0.002
