---
abstract: 'Given a starting date, a number of days and a list of days to be skipped, returns the date X number of days away.'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Perl::Critic::Progressive: 0
  Try::Tiny: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Duration-SkipDays
no_index:
  directory:
    - t
    - xt
provides:
  DateTimeX::Duration::SkipDays:
    file: lib/DateTimeX/Duration/SkipDays.pm
    version: 0.001
requires:
  Carp: 0
  DateTime: 0
  DateTime::Event::Holiday::US: 0
  DateTime::Format::Flexible: 0
resources:
  bugtracker: https://github.com/harleypig/datetimex-duration-skipdays/issues
  repository: git://github.com/harleypig/datetimex-duration-skipdays.git
version: 0.001
